name: Staging DB Snapshot
on:
  workflow_dispatch:
jobs:
  db-staging-snapshot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Snaplet CLI
        run: curl -sL https://app.snaplet.dev/get-cli/ | bash
      - name: Restore Snapshot
        run: snaplet snapshot restore -y
        env:
          SNAPLET_DATABASE_URL: ${{ secrets.SNAPLET_DATA_TARGET_DB_URL }}
          SNAPLET_ACCESS_TOKEN: ${{ secrets.SNAPLET_ACCESS_TOKEN }}
          SNAPLET_DATABASE_ID: ${{ secrets.SNAPLET_DATABASE_ID }}
